- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node

# - name: npmjs prefix
#   shell: mkdir -p ~/.local/.npm-global
#   tags:
#   - install
#   - node

# - name: add npmjs to path
#   shell: PATH=~/.local/.npm-global/bin:$PATH
#   tags:
#   - install
#   - node

# - name: npmjs global settings
#   shell: npm config set prefix '~/.local/.npm-global'
#   tags:
#   - install
#   - node

# - name: npmjs global settings export path in case I don't have dotfiles installed
#   shell: export PATH=~/.local/.npm-global/bin:$PATH
#   tags:
#   - install
#   - node
#   - npm-path

# https://github.com/tj/n
- name: Install node version manager n
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

- name: Install node version 18
  shell: n 18
  tags:
    - install
    - node
